### ISSUE TITLE
TSLint with codelyzer rules 

### ISSUE THREAD

**Issue by aitboudad** [AtomLinter/linter-tslint#127]
Tslint version: `^4.0.2`
Codelyzer version: `^2.0.0-beta.1`

https://github.com/AtomLinter/linter-tslint/pull/124#issuecomment-264983135

```console
Error: Cannot find module 'app-root-path'
Error: Cannot find module 'app-root-path'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at EventEmitter.<anonymous> (/usr/share/atom-beta/resources/electron.asar/browser/rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/share/atom-beta/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/share/atom-beta/resources/electron.asar/renderer/api/remote.js:210:13)
    at Object.exports.require (/usr/share/atom-beta/resources/electron.asar/renderer/api/remote.js:297:10)
    at Object.electron.remote.require (/usr/share/atom-beta/resources/app.asar/src/electron-shims.js:78:28)
    at resolve (/home/my_workspace/node_modules/app-root-path/lib/resolve.js:32:17)
    at module.exports (/home/my_workspace/node_modules/app-root-path/lib/app-root-path.js:6:20)
    at Object.<anonymous> (/home/my_workspace/node_modules/app-root-path/index.js:4:18)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/my_workspace/node_modules/codelyzer/angular/config.js:25:12)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/my_workspace/node_modules/codelyzer/angular/templates/templateParser.js:4:16)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/my_workspace/node_modules/codelyzer/angular/ng2Walker.js:10:24)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/my_workspace/node_modules/codelyzer/noInputRenameRule.js:9:19)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at loadRule (/home/my_workspace/node_modules/tslint/lib/ruleLoader.js:107:26)
    at findRule (/home/my_workspace/node_modules/tslint/lib/ruleLoader.js:82:20)
    at Object.loadRules (/home/my_workspace/node_modules/tslint/lib/ruleLoader.js:33:24)
    at Linter.getEnabledRules (/home/my_workspace/node_modules/tslint/lib/linter.js:163:44)
    at Linter.lint (/home/my_workspace/node_modules/tslint/lib/linter.js:78:33)
    at /home/abdellatif/.atom/packages/linter-tslint/lib/main.js:149:18
```

**Comment by scttcper** [comment]
@aitboudad @Arcanemagus i'm facing the same thing.

I've opened https://github.com/mgechev/codelyzer/pull/177 to fix it.
