### ISSUE TITLE
Cannot find module './core.json'

### ISSUE THREAD

**Issue by iki** [AtomLinter/linter-tslint#134]
**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Microsoft Windows 8 Pro
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package, v0.13.1

### Stack Trace

Failed to activate the linter-tslint package

```
At Cannot find module './core.json'

Error: Cannot find module './core.json'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\iki\.atom\packages\linter-tslint\node_modules\resolve\lib\core.js:12:12)
    at Module._compile (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\iki\.atom\packages\linter-tslint\node_modules\resolve\index.js:1:91)
    at Module._compile (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/iki/.atom/packages/linter-tslint/lib/main.js:7:20)
    at Module._compile (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:766:27)
    at Package.module.exports.Package.activateNow (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:181:16)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:164:32
    at Package.module.exports.Package.measure (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:94:15)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:157:26
    at Package.module.exports.Package.activate (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\atom-environment.js:831:28
```

**Comment by Arcanemagus** [comment]
This codebase has nothing to do with a `core.json` 😕

Maybe this is really due to a different package and the error reporter is just mis-attributing it?

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response.
