### ISSUE TITLE
Failed to activate the linter-tslint package - Cannot find module 'resolve'

### ISSUE THREAD

**Issue by ddavister** [AtomLinter/linter-tslint#135]
Steps to reproduce:

1. Expanded linter-tslint-master.zip in the .\.atom\packages folder
2. Started Atom
3. Saw error below even after retrying.

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package, v0.13.1

### Stack Trace

**Failed to activate the linter-tslint package**

```
**At Cannot find module 'resolve'**

Error: Cannot find module 'resolve'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/999999/.atom/packages/linter-tslint-master/lib/main.js:7:20)
    at Module._compile (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:766:27)
    at Package.module.exports.Package.activateNow (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:181:16)
    at C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:164:32
    at Package.module.exports.Package.measure (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:94:15)
    at C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:157:26
    at Package.module.exports.Package.activate (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\999999\AppData\Local\atom\app-1.13.1\resources\app.asar\src\atom-environment.js:831:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
linter-tslint, v0.13.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Please use `apm install linter-tslint` to install the package. If you really need to install it manually you need to run `apm install` to install all the dependencies.

**Comment by reinouts** [comment]
I was pointed here by Atom's "Failed to activate linter-tslint package" error dialog.
The suggested solution `apm install linter-tslint` does not solve the problem. 
Error info:

[Enter steps to reproduce below:]

1. Update linter-tslint to latest version
2. Start Atom

**Atom Version**: 1.5.4
**System**: "Fedora release
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package, v1.2.0


### Stack Trace

Failed to activate the linter-tslint package

```
At window.requestIdleCallback is not a function

TypeError: window.requestIdleCallback is not a function
    at Object.activate (/home/reinout/.atom/packages/linter-tslint/lib/main.js:37:29)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-elixir"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-tsd, v0.9.0
grunt-runner, v0.14.0
linter, v1.11.18
linter-swagger, v0.3.6
linter-tslint, v1.2.0
select-rectangle, v1.0.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@reinouts Your Atom version is _quite_ old, please update to a newer version.

@Xapphire13 the minimum version of Atom in `package.json` should be bumped up. I'm not entirely sure when Electron began including that, or when Atom would have updated to that, but as `linter` is currently requiring Atom v1.14.0 you might as well bump to that.

**Comment by Arcanemagus** [comment]
Actually, just looked it up, we need a minimum of Atom v1.7.0 for `requestIdleCallback` support.
