### ISSUE TITLE
Uncaught Error: Cannot find module './test/parse'

### ISSUE THREAD

**Issue by jtrinklein** [AtomLinter/linter-tslint#137]
[Enter steps to reproduce:]

1. open project with ts files

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package 0.13.1

### Stack Trace

Uncaught Error: Cannot find module './test/parse'

```
At module.js:457

Error: Cannot find module './test/parse'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jtrinklein/src/myproject/node_modules/tslint/lib/test.js:26:13)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jtrinklein/src/myproject/node_modules/tslint/lib/index.js:29:12)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-tslint/lib/main.js:98:73
    at Object.exports.allowUnsafeNewFunction (/packages/linter-tslint/node_modules/loophole/lib/loophole.js:25:14)
    at /packages/linter-tslint/lib/main.js:98:44
    at /packages/linter-tslint/node_modules/resolve/lib/async.js:45:21
    at ondir (/packages/linter-tslint/node_modules/resolve/lib/async.js:188:31)
    at /packages/linter-tslint/node_modules/resolve/lib/async.js:154:39
    at onex (/packages/linter-tslint/node_modules/resolve/lib/async.js:94:22)
    at /packages/linter-tslint/node_modules/resolve/lib/async.js:25:18
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-ui 1.3.9 
atom-typescript 10.1.14 
cursor-history 0.9.1 
linter 1.11.23 
linter-tslint 0.13.1 
monokai 0.20.0 
```

**Comment by Arcanemagus** [comment]
This looks to be coming from the `tslint` version in your project (`/Users/jtrinklein/src/myproject/node_modules/tslint/lib/test.js`).

**Comment by jtrinklein** [comment]
This turned out to be unrelated to this repo... 
Its a problem with yarn removing files if a `.yarnclean` file is present. Read more about [this issue](https://github.com/palantir/tslint/issues/1770)

**Comment by Arcanemagus** [comment]
Yet another reason to avoid `yarn` for the broken pile of "features" that it is 😛.
