### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by tomitrescak** [AtomLinter/linter-tslint#17]
[Enter steps to reproduce below:]

1. Just updated the plugin, first thing I saw
2. On this Line:   permissions: IPermissionsDA
3. Missing semicolumn

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package, v0.2.2

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Ftomi%2FDocuments%2FProgramming%2FGithub%2FHugosAwesomeWorld%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A313%2C%22initialPaths%22%3A%5B%22%2FUsers%2Ftomi%2FDocuments%2FProgramming%2FGithub%2FHugosAwesomeWorld%22%5D%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at LinterTslint.processMessage (/Users/tomi/.atom/packages/linter-tslint/lib/linter-tslint.coffee:46:34)
  at /Users/tomi/.atom/packages/linter/lib/linter.coffee:182:8
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  3x -0:06.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-monokai"
    ],
    "disabledPackages": [
      "better-handlebars",
      "preview-plus",
      "tree-view-git-status",
      "sublime-tabs",
      "tab-history",
      "atom-handlebars",
      "meteor-helper",
      "enhanced-tabs",
      "close-tags",
      "linter"
    ],
    "ignoredNames": [
      ".settings",
      ".idea",
      ".git",
      ".DS_Store",
      "node_modules",
      "js",
      ".tmp",
      "documentation",
      ".meteor",
      ".build*",
      ".npm"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "linter-tslint": {
    "tslintExecutablePath": "/usr/local/bin/tslint"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Handlebars, v1.1.2
atom-html-preview, v0.1.8
atom-jasmine, v0.6.0
atom-monokai, v0.8.0
atom-typescript, v4.6.6
autoclose-html, v0.18.0
build, v0.38.0
docblockr, v0.7.2
linter, v1.0.5
linter-tslint, v0.2.2
project-manager, v1.15.10
recent-files-fuzzy-finder, v0.1.4
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by tomitrescak** [comment]
try this 

```javascript
  /**
   * @interface IExerciseDAO
   */
  export interface IExerciseDAO extends IAccessSchema {
    _id?: string;
    name: string;
    description: string;
    points: number;
    difficulty: number;
    linesOfCode: ILinesOfCodeDAO;
    worldId: string;
    image: string;
    allowedCommands: string;
    plugins: IPluginDAO[];
    boards: IBoardDAO[];
    images: string[];
    permissions: IPermissionsDAO;
  }
```

**Comment by tjoskar** [comment]
I got the same error:
```
Uncaught SyntaxError: Unexpected end of input

At file:///opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2Flatest%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2Flatest%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A223%2C%22initialPaths%22%3A%5B%22%2FUsers%2Foskar.karlsson%2FProject%2FBoxer%2Fvoyager%2FVoyager.Web%2Ftapas%22%5D%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at LinterTslint.processMessage (/Users/oskar.karlsson/.atom/packages/linter-tslint/lib/linter-tslint.coffee:46:34)
  at /Users/oskar.karlsson/.atom/packages/linter/lib/linter.coffee:182:8
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)
```

I don't know if it is a coincidence but this error started to pop up after I upgraded Atom to 1.0.

**Comment by impinball** [comment]
Is it related to the [upcoming linter changes](https://github.com/AtomLinter/linter-tslint/issues/15)?

**Comment by k2b6s9j** [comment]
@impinball The changes have already happened.

**Comment by impinball** [comment]
I noticed that *after* I replied...

**Comment by park9140** [comment]
@k2b6s9j, @impinball, @tomitrescak, I threw a quick fix together.  I'm still testing but if you could throw it through its paces I deployed 0.4.0 to apm so you can try it.  Report issues on #21

**Comment by evandertino** [comment]
Installing the latest version of **tslint** and **typescript** in my local project, solved the problem
