### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Ascarius** [AtomLinter/linter-tslint#33]
This error append when I'm writing the `as` of an import statement :

```
import {
    List,
    PayloadInterface as|
} from "../../../Console/Responders/Projects/Project/List";
```

```
TypeError: Cannot read property 'length' of undefined
    at NoUseBeforeDeclareWalker.validateUsageForVariable (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/build/rules/noUseBeforeDeclareRule.js:90:41)
    at NoUseBeforeDeclareWalker.visitNamedImports (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/build/rules/noUseBeforeDeclareRule.js:69:18)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:49698:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:49900:40)
    at /home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:49776:67
    at visitNode (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:7197:20)
    at Object.forEachChild (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:7471:21)
    at NoUseBeforeDeclareWalker.SyntaxWalker.walkChildren (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:49776:16)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:49770:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (/home/ascarius/.atom/packages/linter-tslint/node_modules/tslint/lib/tslint.js:49900:40)
```

**Comment by Arcanemagus** [comment]
It looks like this is the same bug as https://github.com/palantir/tslint/issues/583, in any case this is a bug from the `tslint` package, not an issue with this linter plugin so I'm marking it as closed.
