### ISSUE TITLE
Error: formatter 'json' not found

### ISSUE THREAD

**Issue by igabesz** [AtomLinter/linter-tslint#53]
I got the following error in Atom when opening a TS file: Error: formatter 'json' not found. (See trace below.)

I use Windows 8.1, I have tslint available in the PATH. I have installed linter-jsonlint, linter-tslint, linter-eslint and of course the linter package. Plus atom-typescript and others. What's the problem?

```
Error: formatter 'json' not found
  at Linter.lint (C:\Users\G\.atom\packages\linter-tslint\node_modules\tslint\lib\tslint.js:50774:23)
  at Object.provider.lint (C:\Users\G\.atom\packages\linter-tslint\lib\init.coffee:24:23)
  at promises.push.Promise.then._this.emitter.emit.linter (C:\Users\G\.atom\packages\linter\lib\linter-registry.js:95:28)
  at C:\Users\G\.atom\packages\linter\lib\linter-registry.js:94:25
  at Set.forEach (native)
  at LinterRegistry.lint (C:\Users\G\.atom\packages\linter\lib\linter-registry.js:92:20)
  at C:\Users\G\.atom\packages\linter\lib\linter.coffee:98:16
  at Emitter.module.exports.Emitter.emit (C:\Users\G\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at EditorLinter.lint (C:\Users\G\.atom\packages\linter\lib\editor-linter.js:189:20)
  at Commands.lint (C:\Users\G\.atom\packages\linter\lib\commands.coffee:60:40)
  at atom-workspace.Commands.subscriptions.add.atom.commands.add.linter:lint (C:\Users\G\.atom\packages\linter\lib\commands.coffee:13:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\G\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\G\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\G\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at Object.triggerLinter (C:\Users\G\.atom\packages\atom-typescript\dist\main\atom\atomUtils.js:229:19)
  at C:\Users\G\.atom\packages\atom-typescript\dist\main\atomts.js:59:27
```

**Comment by Arcanemagus** [comment]
As that formatter is built into `tslint` that's a pretty bizarre error to run into, have you tried re-installing the plugin?

**Comment by igabesz** [comment]
I have just reinstalled the linter and the linter-tslint packages. Got the same error. Well, I can reinstall the whole Atom stuff if no other clue..

**Comment by igabesz** [comment]
I have reinstalled Atom, it solved the problem. (The packages were kept, I did not have to reinstall them too.)
