### ISSUE TITLE
Could not find the following rules specified in the configuration: no-trailing-comma

### ISSUE THREAD

**Issue by lmarquezMS** [AtomLinter/linter-tslint#66]
Hi, I've the followin error message:

```text
Error: Could not find the following rules specified in the configuration: no-trailing-comma
Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (C:\Users\MY_USERNAME\.atom\packages\linter-tslint\node_modules\tslint\lib\ruleLoader.js:29:15)
    at Linter.lint (C:\Users\MY_USERNAME\.atom\packages\linter-tslint\node_modules\tslint\lib\tslint.js:24:44)
    at file:///C:/Users/MY_USERNAME/.atom/packages/linter-tslint/lib/init.coffee:87:31
```

**Comment by Arcanemagus** [comment]
Does `tslint` in the CLI throw the same error?

**Comment by arusakov** [comment]
@lmarquezMS
As I can see in official tslint docs, ```no-trailing-comma``` is not exist. Use ```trailing-comma``` instead.
