### ISSUE TITLE
Uncaught Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by kerbyfc** [AtomLinter/linter-tslint#71]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package, v0.9.0

### Stack Trace

Uncaught Error: Cannot find module 'typescript'

```
At module.js:338

Error: Cannot find module 'typescript'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kerbyfc/node_modules/tslint/lib/language/utils.js:3:10)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kerbyfc/node_modules/tslint/lib/tslint.js:2:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at /Users/kerbyfc/.atom/packages/linter-tslint/lib/init.coffee:62:22
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:44:21
    at ondir (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:187:31)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:153:39
    at onex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:93:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:24:18
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:05.1.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "update-package-dependencies",
      "styleguide",
      "whitespace",
      "tabs"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "tab-switcher"
    ],
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ],
    "ignoredNames": [
      "*.DS_Store",
      ".git"
    ]
  },
  "linter-tslint": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.4.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
color-picker, v2.1.1
compare-files, v0.6.2
cursor-history, v0.5.9
docblockr, v0.7.3
easy-motion-redux, v1.0.0
editorconfig, v1.2.4
file-icons, v1.6.19
git-diff-details, v1.0.0
highlight-line, v0.11.1
linter, v1.11.4
linter-tslint, v0.9.0
local-settings, v0.4.0
minimap, v4.21.0
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.5.0
minimap-split-diff, v0.3.0
nerd-treeview, v0.4.2
pane-info, v1.0.0
pretty-json, v0.4.1
project-manager, v2.7.6
raml, v0.2.0
smart-tab-name, v1.0.5
space-tab, v0.4.2
tab-length, v0.1.0
tabs-to-spaces, v1.0.2
text-manipulation, v0.6.0
trailing-spaces, v0.3.2
tree-view-git-status, v0.2.3
vim-mode, v0.65.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by arusakov** [comment]
@kerbyfc 
Has local or global typescript package been installed in our project?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.

**Comment by Positive07** [comment]
I replicated this issue, with both TypeScript and TSLint installed globally, both works in the command line but this package fails to use them.

Note that unchecking `Try using local TSLint (if exists)` doesn't fix the issue.

Only installing TypeScript and TSLint locally (with `--save` or `--save-dev`) fixes the issue

**Comment by Xapphire13** [comment]
The code for this package has changed substantially since this bug was filed. If you have a newer stack trace, that would be helpful.

**Comment by Positive07** [comment]
```
<embedded>:70686 Cannot find module 'typescript' Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\username\Documents\Project\node_modules\tslint-eslint-rules\dist\rules\terIndentRule.js:4:10)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\username\AppData\Local\atom\app-1.18.0-beta2\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadRule (C:\Users\username\.atom\packages\linter-tslint\node_modules\tslint\lib\ruleLoader.js:104:26)
    at loadCachedRule (C:\Users\username\.atom\packages\linter-tslint\node_modules\tslint\lib\ruleLoader.js:131:16)
    at findRule (C:\Users\username\.atom\packages\linter-tslint\node_modules\tslint\lib\ruleLoader.js:79:20)
    at Object.loadRules (C:\Users\username\.atom\packages\linter-tslint\node_modules\tslint\lib\ruleLoader.js:36:24)
    at Linter.getEnabledRules (C:\Users\username\.atom\packages\linter-tslint\node_modules\tslint\lib\linter.js:199:44)
    at Linter.lint (C:\Users\username\.atom\packages\linter-tslint\node_modules\tslint\lib\linter.js:76:33)
    at file:///C:/Users/username/.atom/packages/linter-tslint/lib/worker.js:172:12
    at next (<anonymous>)
    at step (file:///C:/Users/username/.atom/packages/linter-tslint/lib/worker.js:204:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Xapphire13** [comment]
I believe you have found a bug in the [tslint-eslint-rules](https://github.com/buzinas/tslint-eslint-rules) project. From the stack trace you posted, `linter-tslint` is calling `tslint`, which then tries to load your custom rules, in this case `tslint-config-standard`, which pulls its rules from `tslint-eslint-rules`, then when loading the rule `terIndentRule`, it hits an error trying to require Typescript:

![image](https://cloud.githubusercontent.com/assets/3392349/26810189/f98ae5e4-4a1e-11e7-817f-21bb8abe266d.png)
Above screenshot from the compiled `tslint-eslint-rules` code for `terIndentRule.ts`

**Comment by Positive07** [comment]
I have no clue on how to report this, could you help me with what exactly is the issue, so I can post it over at tslint-eslint-rules repo?

**Comment by Xapphire13** [comment]
When I have time I'll try to setup a repro on my machine so I can get more details.

**Comment by ccrihan** [comment]
Hi,

same error here.

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/jenkins/workspace/sonar-master/.sonar/Sonar_webclientts/sonarts-core/node_modules/tslint/lib/linter.js:20:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

Using the standard configuration, no personal rules.

**Comment by Arcanemagus** [comment]
@ccrihan What do you get for `npm ls typescript` in your project?

**Comment by ccrihan** [comment]
/var/lib/jenkins/workspace/sonar-master/.sonar/Sonar_webclientts/sonarts-core/node_modules/tslint/lib$ npm ls typescript
tslint@5.4.2 /var/lib/jenkins/workspace/sonar-master/.sonar/Sonar_webclientts/sonarts-core/node_modules/tslint
`-- UNMET PEER DEPENDENCY typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev

npm ERR! peer dep missing: typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev, required by tslint@5.4.2
npm ERR! peer dep missing: typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev, required by tslint@5.4.2
npm ERR! code 1

**Comment by Arcanemagus** [comment]
Looks like that answers your question 😉. Add `typescript` as a dependency to your project as required by using `tslint` and it should work just fine.

**Comment by b1diaz** [comment]
tou can try  npm install @ionic/app-scripts@latest --save-dev

**Comment by agteledom** [comment]
I had a similar problem
Typescript and tslint installed globally. Tslint works fine in one folder but have pretty the same error in adjacent folder.

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```

The problem was that there was a local copy of tslint in problem folder (package.json)
```"tslint": "^5.12.1",```

solution just was to uninstall this local copy
```npm uninstall tslint```
