### ISSUE TITLE
Failed to activate the linter-tslint package

### ISSUE THREAD

**Issue by kematzy** [AtomLinter/linter-tslint#89]
[Enter steps to reproduce below:]

1. Start Atom app

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package, v0.9.3

### Stack Trace

Failed to activate the linter-tslint package

```
At Cannot find module 'tslint'

Error: Cannot find module 'tslint'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.provideLinter (/Users/kematzy/.atom/packages/linter-tslint/lib/init.coffee:69:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:349:69)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoclose-html",
      "pigments"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ""
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-bootstrap4, v1.4.0
atom-typescript, v8.9.1
autocomplete-ruby, v0.1.0
color-picker, v2.1.1
column-select, v0.2.0
emmet, v2.4.3
file-icons, v1.7.10
highlight-selected, v0.11.2
inline-autocomplete, v1.1.0
javascript-snippets, v1.2.1
language-apache, v1.5.0
language-liquid, v0.4.0
linter, v1.11.4
linter-erb, v1.0.2
linter-js-yaml, v1.2.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-sass-lint, v1.4.3
linter-tslint, v0.9.3
minitest-snippets, v0.2.0
open-recent, v5.0.0
ruby-slim, v0.2.0
ruby-syntax-replacer, v0.5.1
term3, v0.22.0
v-bootstrap4, v0.1.7

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? Looks like `apm` failed to install `tslint` to me.

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response. If you are still experiencing this after re-installing the package please let us know.
