### ISSUE TITLE
Uncaught Error: Cannot find module './isBlank'

### ISSUE THREAD

**Issue by alexeden** [AtomLinter/linter-tslint#98]
[Enter steps to reproduce below:]

1. Open a .ts file from the [RxJS source repo](https://github.com/ReactiveX/RxJS).

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-tslint](https://github.com/AtomLinter/linter-tslint) package, v0.10.0

### Stack Trace

Uncaught Error: Cannot find module './isBlank'

```
At module.js:340

Error: Cannot find module './isBlank'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alexeden/Google Drive/code/rxjs/node_modules/tslint/node_modules/underscore.string/index.js:21:22)
    at Module._compile (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alexeden/Google Drive/code/rxjs/node_modules/tslint/lib/formatterLoader.js:4:27)
    at Module._compile (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alexeden/Google Drive/code/rxjs/node_modules/tslint/lib/tslint.js:5:25)
    at Module._compile (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at /Users/alexeden/enveq/share/atom/packages/linter-tslint/lib/init.coffee:62:22
    at /Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:44:21
    at ondir (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:187:31)
    at /Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:153:39
    at onex (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:93:22)
    at /Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/async.js:24:18
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-ternjs",
      "auto-reveal-in-sidebar",
      "atom-htmltidy",
      "api-workbench",
      "linter-sass-lint",
      "linter-scss-lint",
      "atom-wallaby"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules",
      "bower_components",
      "webpack*stats.json"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "remote-sync",
      "atom-htmltidy",
      "terminal-plus",
      "markdown-preview"
    ],
    "projectHome": "/home/alexander/Google\\ Drive/code",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
atom-typescript, v8.11.0
autocomplete-paths, v1.0.2
editorconfig, v1.4.1
file-icons, v1.7.14
indent-guide-improved, v1.4.9
language-elm, v1.5.0
language-haskell, v1.7.17
linter, v1.11.10
linter-eslint, v7.2.2
linter-jade, v0.3.2
linter-jsonlint, v1.2.5
linter-stylelint, v2.11.0
linter-tslint, v0.10.0
markdown-scroll-sync, v2.1.2
markdown-themeable-pdf, v1.0.1
minimap, v4.24.6
pigments, v0.29.2
pretty-json, v1.4.1
tree-view-breadcrumb, v0.8.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
That looks like a bug in `tslint` from the stack trace, does it work from the CLI?

**Comment by Arcanemagus** [comment]
Closing due to lack of response.
